name: "Setup Node.js App"
description: "Checkout, setup Node/PNPM, and install dependencies"

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: 24

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Cache ESLint
      uses: actions/cache@v6
      with:
        path: ${{ inputs.working-directory }}/.eslintcache
        key: ${{ runner.os }}-eslint-${{ inputs.working-directory }}-${{ hashFiles(format('{0}/src/**', inputs.working-directory)) }}
        restore-keys: |
          ${{ runner.os }}-eslint-${{ inputs.working-directory }}-