name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  inspect-code:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-app

      - name: Build (shared code)
        working-directory: ./packages/shared
        shell: bash
        run: pnpm build

      - name: Cache ESLint
        uses: actions/cache@v5
        with:
          path: .eslintcache
          key: ${{ runner.os }}-eslint-${{ hashFiles('eslint.config.mjs', 'backend/src/**', 'frontend/src/**') }}
          restore-keys: |
            ${{ runner.os }}-eslint-

      - name: Run ESLint
        shell: bash
        run: pnpm lint

  backend-test:
    name: (Backend) Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      db:
        image: mariadb:12.2.2
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: psb_sman2_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    env:
      NODE_ENV: test
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: psb_sman2_test
      COOKIE_SECRET: f3a2007d-6344-49f4-8705-f1f9818a86d9
      SESSION_ENCRYPTION_KEY: 6e0eb1287fc4afdc22df1fb5f5c205709347cacbe5ed687bec17a48bf511b995

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-app

      - name: Build
        working-directory: .
        shell: bash
        run: pnpm --filter backend... build

      - name: Run tests
        shell: bash
        run: pnpm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: backend-test-results
          path: ./backend/html/

  frontend-test:
    name: (Frontend) Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-app

      - name: Cache Next.js build cache
        uses: actions/cache@v5
        with:
          path: ./frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('./pnpm-lock.yaml') }}-${{ hashFiles('./frontend/src/**') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('./pnpm-lock.yaml') }}-

      - name: Build
        working-directory: .
        shell: bash
        run: pnpm --filter frontend... build

      - name: Run tests
        shell: bash
        run: pnpm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: frontend-test-results
          path: ./frontend/html/

  e2e-test:
    name: (End-to-End) Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [backend-test, frontend-test]

    services:
      db:
        image: mariadb:12.2.2
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: psb-sman2
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    env:
      NODE_ENV: production
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: psb-sman2
      COOKIE_SECRET: f3a2007d-6344-49f4-8705-f1f9818a86d9
      SESSION_ENCRYPTION_KEY: 6e0eb1287fc4afdc22df1fb5f5c205709347cacbe5ed687bec17a48bf511b995

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-app

      - name: Build
        working-directory: .
        shell: bash
        run: pnpm build

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Push database schema
        working-directory: ./backend
        shell: bash
        run: pnpm drizzle-kit push --force

      - name: Run Playwright tests
        run: pnpm test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: e2e-test-results
          path: ./frontend/playwright-report/