name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  inspect-code:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-app

      - name: Cache ESLint
        uses: actions/cache@v5
        with:
          path: .eslintcache
          key: ${{ runner.os }}-eslint-${{ hashFiles('eslint.config.mjs', 'backend/src/**', 'frontend/src/**') }}
          restore-keys: |
            ${{ runner.os }}-eslint-

      - name: Run ESLint
        shell: bash
        run: pnpm lint

  backend-test:
    name: (Backend) Test
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:12.2.2
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: psb-sman2
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u user -ppassword" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-app

      - name: Build
        shell: bash
        run: pnpm build

      - name: Create test environment file
        run: |
          echo "NODE_ENV=test" >> .env.test
          echo "DB_HOST=127.0.0.1" >> .env.test
          echo "DB_PORT=3306" >> .env.test
          echo "DB_USER=user" >> .env.test
          echo "DB_PASSWORD=password" >> .env.test
          echo "DB_NAME=psb-sman2" >> .env.test
          echo "COOKIE_SECRET=secret" >> .env.test
          echo "SESSION_ENCRYPTION_KEY=${{ secrets.GITHUB_TOKEN }}" >> .env.test

      - name: Wait for MariaDB
        run: |
          for i in {1..10}; do
            mysqladmin ping -h127.0.0.1 -u user -ppassword && break
            echo "Waiting for MariaDB..."
            sleep 3
          done

      - name: Push database schema
        shell: bash
        run: pnpm drizzle-kit push --force

      - name: Run tests
        shell: bash
        run: pnpm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: ./backend/html/

  frontend-test:
    name: (Frontend) Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-app

      - name: Cache Next.js build cache
        uses: actions/cache@v5
        with:
          path: ./frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('./pnpm-lock.yaml') }}-${{ hashFiles('./frontend/src/**') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('./pnpm-lock.yaml') }}-

      - name: Build
        shell: bash
        run: pnpm build

      - name: Run tests
        shell: bash
        run: pnpm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-results
          path: ./frontend/html/

  e2e-test:
    name: (End-to-End) Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [backend-test, frontend-test]

    services:
      db:
        image: mariadb:12.2.2
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: psb-sman2
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u user -ppassword" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-app

      - name: Create production environment file
        run: |
          echo "NODE_ENV=production" >> .env.production
          echo "DB_HOST=127.0.0.1" >> .env.production
          echo "DB_PORT=3306" >> .env.production
          echo "DB_USER=user" >> .env.production
          echo "DB_PASSWORD=password" >> .env.production
          echo "DB_NAME=psb-sman2" >> .env.production
          echo "COOKIE_SECRET=secret" >> .env.production
          echo "SESSION_ENCRYPTION_KEY=${{ secrets.GITHUB_TOKEN }}" >> .env.production
          cp .env.production ../backend/.env.production

      - name: Build
        working-directory: .
        shell: bash
        run: pnpm build

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Wait for MariaDB
        run: |
          for i in {1..10}; do
            mysqladmin ping -h127.0.0.1 -u user -ppassword && break
            echo "Waiting for MariaDB..."
            sleep 3
          done

      - name: Push database schema
        working-directory: ../backend
        shell: bash
        run: pnpm drizzle-kit push --force

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: ./frontend/playwright-report/